=== preston/acraf/acraf.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tgen.org"
	xmlns:tgen="http://www.tgen.org">
	<xs:element name="annotations">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="tgen:annotation" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="annotation">
		<xs:complexType>
			<xs:all>
				<xs:element ref="tgen:disease"/>
				<xs:element ref="tgen:compound"/>
				<xs:element ref="tgen:aberration"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="disease">
		<xs:complexType>
			<xs:attribute name="meshid" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="compound">
		<xs:complexType>
			<xs:attribute name="pubchemid" type="xs:integer" use="required"/>
			<xs:attribute name="name" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="gene">
		<xs:complexType>
			<xs:attribute name="hugoid" type="xs:string" use="required"/>
			<xs:attribute name="entrezid" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pubmed">
		<xs:complexType>
			<xs:attribute name="id" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pathway">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="links">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="tgen:pubmed"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>

	<xs:element name="aberration" abstract="true" type="tgen:aberration-type"/>

	<xs:element name="dna-aberration" substitutionGroup="tgen:aberration"
		type="tgen:dna-aberration-type"> </xs:element>
	<xs:element name="rna-aberration" substitutionGroup="tgen:aberration"
		type="tgen:rna-aberration-type"/>
	<xs:element name="protein-aberration" substitutionGroup="tgen:aberration"/>
	<xs:element name="pathway-aberration" substitutionGroup="tgen:aberration"
		type="tgen:pathway-aberration-type"/>
	<xs:complexType name="aberration-type" abstract="true">
		<xs:all>
			<xs:element ref="tgen:description"/>
			<xs:element minOccurs="0" ref="tgen:gene"/>
			<xs:element minOccurs="0" ref="tgen:pathway"/>
			<xs:element ref="tgen:links"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute form="unqualified" name="phenotype" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="sensitivity"/>
					<xs:enumeration value="resistence"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="cosmicid" type="xs:string"/>
		<xs:attribute name="priority" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="high"/>
					<xs:enumeration value="medium"/>
					<xs:enumeration value="low"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="dna-aberration-type">
		<xs:complexContent>
			<xs:extension base="tgen:aberration-type">
				<xs:attribute name="level">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="substitution"/>
							<xs:enumeration value="insertion"/>
							<xs:enumeration value="deletion"/>
							<xs:enumeration value="translocation"/>
							<xs:enumeration value="gain"/>
							<xs:enumeration value="loss"/>
							<xs:enumeration value="snp"/>
							<xs:enumeration value="hypermethylated"/>
							<xs:enumeration value="hypomethylated"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="rna-aberration-type">
		<xs:complexContent>
			<xs:extension base="tgen:aberration-type">
				<xs:attribute name="level">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="up"/>
							<xs:enumeration value="down"/>
							<xs:enumeration value="unchanged"/>
							<xs:enumeration value="fusion"/>
							<xs:enumeration value="splice"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="protein-aberration-type">
		<xs:complexContent>
			<xs:extension base="tgen:aberration-type"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="pathway-aberration-type">
		<xs:complexContent>
			<xs:extension base="tgen:aberration-type">
				<xs:attribute name="level">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="activated"/>
							<xs:enumeration value="inhibited"/>
							<xs:enumeration value="altered"/>
							<xs:enumeration value="up"/>
							<xs:enumeration value="down"/>
							<xs:enumeration value="unchanged"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== preston/acraf/generated/fake2.xml
<?xml version="1.0" encoding="UTF-8"?>
<annotation xmlns="http://www.tgen.org"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tgen.org file:/Users/preston/Developer/git/acraf/acraf.xsd">
    <disease meshid="nQMAG1y"/>
    <compound pubchemid="-863457491" name="RG5g49vovfWWQNvBtBdOva"/>
    <protein-aberration xmlns:tgen="http://www.tgen.org" xsi:type="tgen:dna-aberration-type" level="substitution" name="td6wO_Pd" phenotype="resistence" cosmicid="Mdnpo6zvZ7e" priority="low">
        <description>Cd</description>
        <gene hugoid="ZF74ufd_JRSjYJa1nV3hQDAiJzJww" entrezid="_nKvQqqHdamh-lzrZT"/>
        <pathway name="iC0TylV33PCN.u"/>
        <links>
            <pubmed id="-442312361"/>
            <pubmed id="1263000279"/>
            <pubmed id="1105351940"/>
        </links>
    </protein-aberration>
</annotation>

=== preston/acraf/generated/fake3.xml
<?xml version="1.0" encoding="UTF-8"?>
<annotations xmlns="http://www.tgen.org"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tgen.org file:/Users/preston/Developer/git/acraf/acraf.xsd">
    <annotation>
        <disease meshid="uxf5pCke-imC"/>
        <compound pubchemid="-177006436" name="h"/>
        <pathway-aberration level="unchanged" name="NZMVxo" phenotype="sensitivity" cosmicid="G195-Vj7XqtH" priority="high">
            <description>iwp6UhOXnso0dO_pZ</description>
            <gene hugoid="dTMttgCsf6wh.R.iZdMTv2QWw1zs4" entrezid="Q44580OKp2lFPs9E"/>
            <pathway name="TOSaPuqHw"/>
            <links>
                <pubmed id="-236486115"/>
                <pubmed id="299367163"/>
                <pubmed id="-569097068"/>
            </links>
        </pathway-aberration>
    </annotation>
    <annotation>
        <disease meshid="zV9jJrE64csfQoY9PXxTB.ZQo"/>
        <compound pubchemid="-711306718" name="o7YWBe.PCgQh15MM27TbBio3q2"/>
        <rna-aberration level="unchanged" name="Eg4t" phenotype="sensitivity" cosmicid="Yd" priority="high">
            <description>lv0DN</description>
            <gene hugoid="oP_" entrezid="ZdMEPeMt4sU"/>
            <pathway name="TjlzBQb5AXPt8gW5UwXpUqw7Fe.yZ."/>
            <links>
                <pubmed id="166501073"/>
                <pubmed id="1116055780"/>
                <pubmed id="272714719"/>
            </links>
        </rna-aberration>
    </annotation>
    <annotation>
        <disease meshid="KzH"/>
        <compound pubchemid="1634026058" name="NJwFf_D"/>
        <protein-aberration xmlns:tgen="http://www.tgen.org" xsi:type="tgen:rna-aberration-type" level="fusion" name="UIuMvUkaSTtbB-E2pT_3vY" phenotype="sensitivity" cosmicid="TCjuz3Qa5MgR5L2ljRMfOq"
             priority="high">
            <description>rZ6dS-AH0ler5q9.EqSZ.</description>
            <gene hugoid="mHzcS-wQWVzP3mOyQbOd66g" entrezid="SaWSl_qWXNj8coB11BaZAcPx4"/>
            <pathway name="LKLEPG"/>
            <links>
                <pubmed id="584411380"/>
                <pubmed id="-2041098206"/>
                <pubmed id="-1175720151"/>
            </links>
        </protein-aberration>
    </annotation>
</annotations>

=== preston/acraf/generated/fake4.xml
<?xml version="1.0" encoding="UTF-8"?>
<annotations xmlns="http://www.tgen.org"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tgen.org file:/Users/preston/Developer/git/acraf/acraf.xsd">
    <annotation>
        <disease meshid="H4zvpQDJWjTd5cN"/>
        <compound pubchemid="-75152154" name="K"/>
        <rna-aberration level="splice" name="NOrf" phenotype="resistence" cosmicid="bYDJtn23LHzrlr2Rh.l16uR5" priority="medium">
            <description>dM6mZLA</description>
            <gene hugoid="mVeu0" entrezid="iS3NH_lEAOJy44HWvKEjKsUaIYFHc"/>
            <pathway name="AuPEG_HrZb2dtzUUdz"/>
            <links>
                <pubmed id="1356344106"/>
                <pubmed id="-1132884417"/>
                <pubmed id="1951461443"/>
            </links>
        </rna-aberration>
    </annotation>
    <annotation>
        <disease meshid="cw29Omjus1"/>
        <compound pubchemid="1260012866" name="gtHA.PgIsc03slGl"/>
        <rna-aberration level="unchanged" name="pyYVKxz3dkUh59lAVDp7s..Z9EK" phenotype="sensitivity" cosmicid="EF_7bazADvuLz87U9iTz."
             priority="high">
            <description>volbDwcOySC5_kbDecA</description>
            <gene hugoid="hXpYCQK8xuN8dm5-GHuDt" entrezid="XlJ02LLCqchN9"/>
            <pathway name="tb_jbjAicg-HDOc-3kzjqAXmMK"/>
            <links>
                <pubmed id="-929050841"/>
                <pubmed id="61888166"/>
                <pubmed id="1716617774"/>
            </links>
        </rna-aberration>
    </annotation>
    <annotation>
        <disease meshid="MPvLVat0rh_o"/>
        <compound pubchemid="-789425990" name="oLx5Oo-Gisv0gl8-eKP"/>
        <protein-aberration xmlns:tgen="http://www.tgen.org" xsi:type="tgen:rna-aberration-type" level="down" name="oxBnfYDZbOOG3ZRS81mh6jjfaO6XbK" phenotype="sensitivity" cosmicid="ogv_6UJOqY2_HpRACVjD9CaSxWoi"
             priority="medium">
            <description>hK7Sk</description>
            <gene hugoid="gsPrd9clCgiUH8s04yagNz_Gn" entrezid="u"/>
            <pathway name="ZSx0VHZIXw.lh"/>
            <links>
                <pubmed id="-127546795"/>
                <pubmed id="403285158"/>
                <pubmed id="1196887094"/>
            </links>
        </protein-aberration>
    </annotation>
</annotations>

=== preston/acraf/generated/fake1.xml
<?xml version="1.0" encoding="UTF-8"?>
<annotations xmlns="http://www.tgen.org"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.tgen.org file:/Users/preston/Desktop/Aberration%20Drug%20Response%20Annotation%20Exchange/acraf.xsd">
    <annotation>
        <disease meshid="mrzVZ2NxvwfCJ9w9A"/>
        <compound pubchemid="293428843" name="r"/>
        <aberration name="zT5WZw" phenotype="resistence">
            <description>PNlbYwchrr</description>
            <gene hugoid="QsNXK49aH_2l" entrezid="nvvoTh3.-H3pST3SK5XGq7-QRFxUct"/>
            <pathway name="npI67ggp._Th9PXhaAZ-"/>
            <links>
                <pubmed id="-1005758997"/>
                <pubmed id="-2041379640"/>
                <pubmed id="194629053"/>
            </links>
        </aberration>
    </annotation>
    <annotation>
        <disease meshid="FCD8dtfr"/>
        <compound pubchemid="33556060" name="UQ"/>
        <aberration name="ptVJOJQBjwEg.wSQbMi2M" phenotype="sensitivity">
            <description>S8KQJzqKdmAAqWR0</description>
            <gene hugoid="YfET44qq2uCwAVqq" entrezid="hN_u6xHb"/>
            <pathway name="lu-pAMPvDbFqPHYshzhcWo9"/>
            <links>
                <pubmed id="2076513730"/>
                <pubmed id="-1378664763"/>
                <pubmed id="869592671"/>
            </links>
        </aberration>
    </annotation>
    <annotation>
        <disease meshid="I7mkPJdvcLJHZu65aP"/>
        <compound pubchemid="-1931954719" name="Y5G"/>
        <aberration name="_ggmCCX-inooFtmqTpuASIe_eKGM" phenotype="sensitivity">
            <description>S1F0bWE4bhcxzwTHz</description>
            <gene hugoid="thBgOgLFpKX-UulT80" entrezid="bSADlBMUNWk"/>
            <pathway name="dsRSr2j_4StECw"/>
            <links>
                <pubmed id="-1137259642"/>
                <pubmed id="806808060"/>
                <pubmed id="-218085316"/>
            </links>
        </aberration>
    </annotation>
</annotations>
